### ISSUE TITLE
ValueError: invalid shape in fixed-type tuple: dtype size in bytes must fit into a C int.

### ISSUE THREAD

**Issue by zayfod** [thtrieu/darktf#10]
When I try to use yolo.cfg with the 753 MB yolov1.weights (renamed to bin/yolo.weights) from http://pjreddie.com/darknet/yolov1/, I get the below numpy error:

```
$ python flow --testset datas/ --model yolo --threshold 0.1 --gpu 0.8
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
Parsing ./configs/yolo.cfg
Last convolutional kernel size = 26.5098364494
Loading ./bin/yolo.weights ...
Traceback (most recent call last):
  File "flow", line 31, in <module>
    darknet = Darknet(FLAGS)
  File "/home/ktenchov/work/yolotf/darknet/darknet.py", line 36, in __init__
    self.load_weights(weight_file)
  File "/home/ktenchov/work/yolotf/darknet/darknet.py", line 61, in load_weights
    l.load(loader)
  File "/home/ktenchov/work/yolotf/darknet/darkop.py", line 76, in load
    weight_array = loader(weight_size)
  File "/home/ktenchov/work/yolotf/darknet/darkop.py", line 16, in __call__
    dtype = '({})float32,'.format(length))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/memmap.py", line 225, in __new__
    descr = dtypedescr(dtype)
ValueError: invalid shape in fixed-type tuple: dtype size in bytes must fit into a C int.
```

Using yolo-tiny.cfg with the 103 MB tiny-yolo.weights (renamed to bin/yolo-tiny.cfg)

I wonder whether I am missing something obvious?

I am using darktf revision c96324546 on a 64-bit Ubuntu 14.04 LTS machine. Here are the relevant Python dependencies:
```
$ pip list
numpy (1.11.2)
pip (1.5.4)
scipy (0.13.3)
tensorflow (0.11.0)
```

**Comment by thtrieu** [comment]
Well, it's just that both 753 and 103 MB yolo are new and I am still finding time to work on some new layer they require, namely, batch norm and local layers. 

I have been refactoring code a lot lately, hoping that people being able to read it will help me out.
