### ISSUE TITLE
ImportError: cannot import name 'ensure_dir_exists'

### ISSUE THREAD

**Issue by ankitAMD** [thtrieu/darktf#1146]
(abc) assetone04@assetone04-Vostro-3490:~/Music/lending-club-loan-data$ jupyter-notebook 

Traceback (most recent call last):   File "/home/assetone04/anaconda2/envs/abc/bin/jupyter-notebook", line 7, in <module>   
  from notebook.notebookapp import main   
File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>     from .nbextensions import install_nbextension   
File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/notebook/nbextensions.py", line 22, in <module>     
from jupyter_core.utils import ensure_dir_exists 
ImportError: cannot import name 'ensure_dir_exists'

**Comment by ankitAMD** [comment]
update jupyter core

                       pip install jupyter-core --upgrade
 
this working for me in Anaconda3 with python 3.6

https://stackoverflow.com/questions/48372019/importerror-cannot-import-name-ensure-dir-exists
