### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by ankitAMD** [thtrieu/darktf#1147]
(abc) assetone04@assetone04-Vostro-3490:~/Music/lending-club-loan-data$ jupyter notebook
[I 15:58:53.734 NotebookApp] Serving notebooks from local directory: /home/assetone04/Music/lending-club-loan-data
[I 15:58:53.734 NotebookApp] The Jupyter Notebook is running at:
[I 15:58:53.734 NotebookApp] http://localhost:8888/?token=860784b5708dc15e063cc73c49f9adb38f29a90202a54124
[I 15:58:53.734 NotebookApp]  or http://127.0.0.1:8888/?token=860784b5708dc15e063cc73c49f9adb38f29a90202a54124
[I 15:58:53.734 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:58:53.738 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/assetone04/.local/share/jupyter/runtime/nbserver-7367-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=860784b5708dc15e063cc73c49f9adb38f29a90202a54124
     or http://127.0.0.1:8888/?token=860784b5708dc15e063cc73c49f9adb38f29a90202a54124
[I 15:59:06.883 NotebookApp] Kernel started: 43252552-72c5-4aff-98be-14be7bf834f9
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.application:Exception in callback functools.partial(<function ZMQStream._update_handler.<locals>.<lambda> at 0x7fe0743
Traceback (most recent call last):
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 542, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 456, in _handle_events
    self._handle_recv()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 486, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 438, in _run_callback
    callback(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
Traceback (most recent call last):
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instan
    app.start()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/assetone04/anaconda2/envs/abc/lib/python3.6/asyncio/base_events.py", line 408, in run_forever

RuntimeError: This event loop is already running

@thtrieu @abagshaw  PLease help .......................

**Comment by ankitAMD** [comment]
i solve this issue in several steps .........i don't know about technical knowledge of this issue but in my case  i tell you about how i solve.....

                          1. First i type on terminal to check packages ...... 
                             conda list

                          2. After then i see there are two tornado packages one are installed by pip and other are installed by conda . tornado 6.0.0 version are installed by pip and tornado:   4.5.2-py36_0. version are installed by conda

                          3. after then i uninstalled "tornado of conda version" using command  
                                  conda uninstall tornado 
                           so uninstalling tornado automatically  ipykernel: 4.6.1-py36_0 are also uninstalled.

                           4. again i installed tornado 
                              conda install tornado

                           5. after than i run jupyter notebook it shows error 
                               "  /home/assetone04/anaconda2/envs/abc/bin/python: No module named ipykernel_launcher "
                            
                             6. after then i install
                               pip install ipykernel

  after this passing below command on terminal, the notebook runs properly.
                            
                                " jupyter notebook "
