### ISSUE TITLE
AssertionError: bin/yolo.weights not found

### ISSUE THREAD

**Issue by gcovillo** [thtrieu/darktf#1155]
I know this has been mentioned before but I still cannot figure out where this bin folder is? 

**Error Code:**

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:15: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:16: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:17: The name tf.train.AdagradOptimizer is deprecated. Please use tf.compat.v1.train.AdagradOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:18: The name tf.train.AdagradDAOptimizer is deprecated. Please use tf.compat.v1.train.AdagradDAOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:19: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:20: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:21: The name tf.train.FtrlOptimizer is deprecated. Please use tf.compat.v1.train.FtrlOptimizer instead.

WARNING:tensorflow:From C:\Users\gcovillo\darkflow-master\darkflow\net\build.py:22: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "C:\Users\gcovillo\darkflow-master\darkflow\cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "C:\Users\gcovillo\darkflow-master\darkflow\net\build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "C:\Users\gcovillo\darkflow-master\darkflow\dark\darknet.py", line 13, in __init__
    self.get_weight_src(FLAGS)
  File "C:\Users\gcovillo\darkflow-master\darkflow\dark\darknet.py", line 47, in get_weight_src
    '{} not found'.format(FLAGS.load)
AssertionError: bin/yolo.weights not found

**Additional Documentation : **
This is where I have been documenting my long-lasting struggle to get darkflow to work:
https://github.com/tensorflow/tensorflow/issues/37906 

![darkflowhallp](https://user-images.githubusercontent.com/40395875/77665634-501a6880-6f56-11ea-8bb5-c591013aeea9.PNG)

Fixed this: I was not in the correct folder. Had to go to C:\Users:\
Also in my main file I was using the format

**Comment by gcovillo** [comment]
File "darkflowEx.py", line 4
    options = {"model": "C:\Users\gcovillo\darkflow-master\cfg\yolo.cfg",
                       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape


Fixed this by ignoring the original code i wrote and just following 
python flow --h
then i did 
python flow --model cfg/yolo.cfg
^^^ this sets the model 

https://github.com/thtrieu/darkflow

follow this instead
