### ISSUE TITLE
'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Qian1995** [thtrieu/darktf#1179]
目的是做车牌号视频识别，采用了自己的数据集然后重建了train文件夹，运用python flow --model cfg/tiny-yolo-3c.cfg --load bin/tiny-yolo-voc.weights --train --annotation train/Annotations --dataset train/Images
开始训练后出现这种情况，求解答！
黑: 132
6: 2141
G: 377
鲁: 161
吉: 281
X: 211
1: 2059
澳: 24
新: 5
F: 538
鄂: 381
S: 309
4: 682
苏: 200
plate: 4979
W: 160
D: 822
云: 60
京: 125
Dataset size: 4982
Dataset of 4982 instance(s)
Traceback (most recent call last):
  File "flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ubuntu/MyFiles/darkflow/darkflow/cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/ubuntu/MyFiles/darkflow/darkflow/net/flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/ubuntu/MyFiles/darkflow/darkflow/net/yolo/data.py", line 114, in shuffle
    inp, new_feed = self._batch(train_instance)
  File "/home/ubuntu/MyFiles/darkflow/darkflow/net/yolov2/data.py", line 27, in _batch
    img = self.preprocess(path, allobj)
  File "/home/ubuntu/MyFiles/darkflow/darkflow/net/yolo/predict.py", line 62, in preprocess
    result = imcv2_affine_trans(im)
  File "/home/ubuntu/MyFiles/darkflow/darkflow/utils/im_transform.py", line 20, in imcv2_affine_trans
    h, w, c = im.shape
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by k66inthesky** [comment]
Hi，我遇過類似的問題，
我的解法是檢查自己的xml與jpg檔名對應、xml的內容有行檔名也要對應至jpg。
希望有幫到你～

**Comment by Qian1995** [comment]
您好！已经收到您的建议，我今天也解决了这个问题，解决方法和您一样，把predict.py文件中的im打印后发现后面没有加.jpg的后缀，加了之后已经可以运行了，十分感谢您的解答！
