### ISSUE TITLE
NMS.pxd not found

### ISSUE THREAD

**Issue by LeoYaMM** [thtrieu/darktf#1223]
I have already installed nms but on my terminal i got this issue
\darkflow\setup.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp
Compiling darkflow/cython_utils/nms.pyx because it changed.
Compiling darkflow/cython_utils/cy_yolo2_findboxes.pyx because it changed.
Compiling darkflow/cython_utils/cy_yolo_findboxes.pyx because it changed.
[1/3] Cythonizing darkflow/cython_utils/cy_yolo2_findboxes.pyx
\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Cython\Compiler\Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: C:\Users\yleob\darkflow\darkflow\cython_utils\cy_yolo2_findboxes.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cimport numpy as np
cimport cython
ctypedef np.float_t DTYPE_t
from libc.math cimport exp
from ..utils.box import BoundBox
from nms cimport NMS
^
------------------------------------------------------------

darkflow\cython_utils\cy_yolo2_findboxes.pyx:7:0: 'nms\NMS.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
                    if(tempc > threshold):
                        probs[row, col, box_loop, class_loop] = tempc

    #NMS
    return NMS(np.ascontiguousarray(probs).reshape(H*W*B,C), np.ascontiguousarray(Bbox_pred).reshape(H*B*W,5))
           ^
------------------------------------------------------------

darkflow\cython_utils\cy_yolo2_findboxes.pyx:97:11: 'NMS' is not a constant, variable or function identifier
Traceback (most recent call last):
  File "\darkflow\setup.py", line 73, in <module>
    ext_modules = cythonize(ext_modules)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: darkflow/cython_utils/cy_yolo2_findboxes.pyx

Do anyone knows how to fix it?

**Comment by yujia-wa** [comment]
In /darkflow-master/darkflow/cython_utils/cy_yolo2_findboxes.pyx and /darkflow-master/darkflow/cython_utils/cy_yolo_findboxes.pyx, update "from .nms cimport NMS".

**Comment by gubi** [comment]
> In /darkflow-master/darkflow/cython_utils/cy_yolo2_findboxes.pyx and /darkflow-master/darkflow/cython_utils/cy_yolo_findboxes.pyx, update "from .nms cimport NMS".

My original error was caused by a [darkflow](https://github.com/thtrieu/darkflow) bug in installation.

@yujia-wa solved me:
![image](https://github.com/user-attachments/assets/a7e0c40f-f401-4048-8133-e6c9e98e9793)

👍🏻
