### ISSUE TITLE
How to run/test Yolo converted .pb file on Tensorflow

### ISSUE THREAD

**Issue by harshiddhmania** [thtrieu/darktf#574]
Hi,

I am beginner and converted darkflow weights file into the .pb file. Now i want to run/test this .pb file on Temsorflow. So how should i do that?

I tried executing lable_image example of tensorflow, with my new converted model "frozen_model_02072018.pb", but i am getting error message as shown below.

**VirtualBox tensorflow$** python tensorflow/examples/label_image/label_image.py --graph=tensorflow/examples/label_image/data/frozen_model_02072018.pb --image=tensorflow/examples/label_image/data/sample_dog.jpg 
2018-02-08 11:16:42.890744: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2
Traceback (most recent call last):
  File "tensorflow/examples/label_image/label_image.py", line 134, in <module>
    input_operation.outputs[0]: t
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1104, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 448, 448, 3) for Tensor u'import/mul:0', which has shape '(?, 224, 224, 64)'

Has anyone tried this? Please help to run it on Tensorflow. 

Thanks in advanced!

**Comment by pshwetank** [comment]
There seems to be some issue with the input dimensions of the converted tensor. Especially, the first dimension which is '?'

**Comment by pshwetank** [comment]
Can you tell which version of Yolo you implemented? It will help me understand your issue better.
