### ISSUE TITLE
Prediction gone wrong (hundreds of overlapping Bounding Boxes)

### ISSUE THREAD

**Issue by rphly** [thtrieu/darktf#724]
This is what I get when I load the trained model: 

![test](https://user-images.githubusercontent.com/23185489/38811235-9b1ad330-41bb-11e8-8bdf-7d21ac4fd678.jpg)

I'm not sure what's happening?

I'm also getting an error after around 2671+ steps: 
```
Traceback (most recent call last):
  File "./flow", line 6, in <module>
    cliHandler(sys.argv)
  File "/home/ec2-user/license_plate/darkflow/cli.py", line 33, in cliHandler
    print('Enter training ...'); tfnet.train()
  File "/home/ec2-user/license_plate/darkflow/net/flow.py", line 39, in train
    for i, (x_batch, datum) in enumerate(batches):
  File "/home/ec2-user/license_plate/darkflow/net/yolo/data.py", line 132, in shuffle
    x_batch = np.concatenate(x_batch, 0)
ValueError: need at least one array to concatenate
```

**Comment by rphly** [comment]
I'm starting to think the first error might have something to do with a low threshold?

**Comment by zxczhkzxc** [comment]
do you solve this problem, i meet the same @rphly

**Comment by hylovezhang** [comment]
I also have this issue,
